### ISSUE TITLE
Extractor cuts out last two lines of test sample code during CI

### ISSUE THREAD

**Issue by loziniak** [exercism/snippet-extractor#66]
(refs #62 )
Hello. I'm trying to sort things out with extractor config for Red. In my simple test a strange thing is going on during CI tests – sample code is truncated by 2 lines for some reason.

https://github.com/exercism/snippet-extractor/actions/runs/3725287654/jobs/6318000198

a log from CI job:

```
Run options: --seed 5372

# Running:

.......................................................................................F................................................

SimpleCov failed with exit 1rake aborted!
Finished in 0.109589s, 1240.9994 runs/s, 1250.1244 assertions/s.
Command failed with status (1)
/home/runner/work/snippet-extractor/snippet-extractor/vendor/bundle/ruby/2.6.0/gems/rake-13.0.1/exe/rake:27:in `<top (required)>'
/opt/hostedtoolcache/Ruby/2.6.6/x64/bin/bundle:23:in `load'
/opt/hostedtoolcache/Ruby/2.6.6/x64/bin/bundle:23:in `<main>'
Tasks: TOP => test
(See full trace by running task with --trace)

  1) Failure:
SnippetExtractor::Languages::RedTest#test_full_example [/home/runner/work/snippet-extractor/snippet-extractor/test/languages/red_test.rb:47]:
--- expected
+++ actual
@@ -8,6 +8,4 @@
 function add100 [x [integer!]] [
 \t\" this should not count as comment \"
 \t{ and neither
-\t this }
-]
 "


136 runs, 137 assertions, 1 failures, 0 errors, 0 skips
Coverage report generated for Unit Tests to /home/runner/work/snippet-extractor/snippet-extractor/coverage. 871 / 877 LOC (99.32%) covered.
```

**Comment by joshiraez** [comment]
It's intentional. The snippet extractor will only get the top 10 lines from the code as it's what fits inside exercism ui (and is a leftover from the basic mode).  I thought I implemented an option to increase the number of lines but it was left out of scope. In any case, I should update the Readme stating explicitly that it will only get the first 10 valid lines,

(Technically, the snippet extractor will correctly extract the 12 lines but you can check in the code that only the first 10 lines are then retrieved: https://github.com/exercism/snippet-extractor/blob/4c7481559fc9b1a429c8e487618cc7ba080da363/lib/snippet_extractor/extended/extract.rb#L14)

**Comment by loziniak** [comment]
Tests now pass OK.
